### ISSUE TITLE
Upload tutorial examples

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOL_website#100]
Put all documentation on github.io

For every language provide the following example:
i) Very simple gene cassette (See C/C++ example)
ii) Put together a toggle switch example 
iii) CRISPR

Provide a developers FAQ. List simple operations, eg sequence create sequence, join parts etc, this should be for all languages

**Comment by cjmyers** [comment]
Move this to the library trackers.

**Comment by tramyn** [comment]
This issue request is now redirected to each SBOL library:
[sboljs (javascript)](https://github.com/SynBioDex/sboljs/issues/11), [libSBOL (C, C++)](https://github.com/SynBioDex/libSBOL/issues/143), [pySBOL (python)](https://github.com/SynBioDex/pySBOL/issues/44), and [libSBOLj (java)](https://github.com/SynBioDex/libSBOLj/issues/444)
