### ISSUE TITLE
steering committee email address doesn't work

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL_website#101]
steering-committee@sbolstandard.org does not work.  Need to either fix it on change the address.
The other @sbolstandard.org email addresses should also be checked.

**Comment by tramyn** [comment]
@jakebeal Based On our meeting with the SBOL developers on Feb. 17th, 2017, we have decided to migrate all @sbolstandard.org e-mail addresses to @googlegroups.com. By switching over to google groups, this will allow the future editors and developers to have easier management to add and remove members to the SBOL team. I have gone and changed all e-mails that refer to sbolstandard.org to point to googlegroups.com on the website. These changes have been made on all Pages and Posts made to the SBOL website. 

steering-committee@sbolstandard.org to sbol-steering@googlegroups.com
editors@sbolstandard.org to sbol-editors@googlegroups.com
visual@sbolstandard.org to sbol-visual@googlegroups.com
