### ISSUE TITLE
Modifying Community->Developer Group Map

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOL_website#102]
If would be nice to make the map found in Community->Developer Group Map to have more location points to represent more members in the SBOL-dev community. Currently, the map looks like it has 1 point that covers a group of people rather than 1 point per person. 

Another option is to highlight over the region (i.e. states and countries) that the group of people are residing in.

**Comment by tramyn** [comment]
@cjmyers @jakebeal :

The map is now updated for all 112 SBOL members recorded on our SBOL member stats document. What this map does not show are the duplicate entires for the same institution or organization. This means that if there are 6 members from the University of Utah, only one marking will show on the map. There were 4 institutions that could not be added to the map because they either did not have a physical address or Google Map could not locate it (i.e. Genome Compiler, GenoCAD, Eight Pillars Ltd, UK, and Turing Ate My Hamster, Ltd.)

http://sbolstandard.org/development/developers/

If you are happy with the changes, please close this issue. Else, let me know what changes you want to make.

**Comment by cjmyers** [comment]
GenomeCompiler is in CA, see:

http://www.genomecompiler.com <http://www.genomecompiler.com/>

GenoCad is in Virginia Tech in Blackburg VA

Turing ate my hamster is Newcastle

Eight Pillars in Edinburgh, UK

Chris

**Comment by jakebeal** [comment]
Do you have a procedure in place for maintaining the map over time? That is a necessary part of this issue as well.

**Comment by tramyn** [comment]
@jakebeal There is a way to manage the map over time and that's using Google Map Marker XML files. These are useful when you have large amount of markings you want to upload to the map every time. We would need to figure out how to generate the XML for this. 

For now, I went in and manually added the individual markings. Due to the deadline that we are given, this request will have to be pushed to future implementation.

**Comment by tramyn** [comment]
@cjmyers I have updated the the 4 companies that you have listed to the map.
