### ISSUE TITLE
Typo / Broken Links

### ISSUE THREAD

**Issue by nathanwilk7** [SynBioDex/SBOL_website#118]
1. http://sbolstandard.org/ - Intro Paragraph: "biology community and scientist working" - scientist is typo, should be scientists
2. http://sbolstandard.org/data-model-specification/ - Library Implementation link: Link goes to http://sbolstandard.org/software/libraries/, which gives "Page not found" error
3. http://sbolstandard.org/downloads/specifications/specification-data-model-2-0-0/ - JS SBOL Core Specification 2.0 link: Link goes to http://sbolstandard.org/downloads/specifications/specification-data-model-2-0-0/, which gives "Page not found" error

**Comment by tramyn** [comment]
Grammatical suggestion for issue 1 is updated on the main webpage.
Broken links for issue 2 and 3 have been updated as well.
