### ISSUE TITLE
Missing SVG glyphs

### ISSUE THREAD

**Issue by shyambhakta** [SynBioDex/SBOL_website#119]
The SBOL Visual 2.0.0 "Nucleic Acid Glyphs SVG" file [[here]](http://sbolstandard.org/visual/glyphs/) doesn't contain the glyphs for:
1. engineered region
2. poly-A site
3. primer binding site
4. promoter
5. ribosome entry site
6. signature
7. recombination site
8. terminator

**Comment by tramyn** [comment]
@shyambhakta Thank you for reporting this issue. I have updated the SBOL website to include the eight glyphs that were missing. The new changes are available [here](http://sbolstandard.org/visual/glyphs/).
If you are satisfied with the changes, feel free to close this issue. If not, let me know what is missing and we will continue to make the necessary fixes.
