### ISSUE TITLE
Broken links/images

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SBOL_website#120]
I noticed several broken links within the SBOL website, so ran [linkchecker](https://github.com/linkchecker/linkchecker) to generate a complete list.

## Broken links:

http://sbolstandard.org/libsbol/ has a 'software tools ' link to http://sbolstandard.org/software/tools/  rather than http://sbolstandard.org/applications/

http://sbolstandard.org/applications/ has a link to http://sbolstandard.org/applications/www.cellocad.org rather than http://wwww.cellocad.org

http://sbolstandard.org/contact/ has a broken 'Members' link

http://sbolstandard.org/libsbolj-2-2-1-release has a broken 'SBOL Website' link 

http://sbolstandard.org/libsbol-2-1-1-release has a broken link to http://sbolstandard.org/software/libsbol/cc/

http://sbolstandard.org/sbol-2-1-0-released has a broken 'SBOL website' link

http://sbolstandard.org/sbol-2-0-released has a broken '2.0 beta release of libSBOLj' link 

http://sbolstandard.org/development/meetings/sbol-workshop-seattle-wa-2012 has a broken link to the workshop agenda

http://sbolstandard.org/development/meetings/synthetic-biology-data-exchange-group-meeting-stanford-ca-2009 has a broken link to the attachment "Galdzicki_PoBoL_Update_26072009.pptx"

## Broken ``img`` tags:

http://sbolstandard.org/development/outreach has incorrect URLs for embedded images (soundbio2.png, soundbio5.png, soundbio6.png, soundbio7.png, soundbio8.png)

http://sbolstandard.org/libsbolj-2-2-1-release has an incorrect URL for libSBOLj_2-2-1.png

http://sbolstandard.org/development/meetings/sbol-workshop-seattle-wa-2012 has incorrect URLs for coffee.png, SBOLWorkshopDirections.png, SBOLWorkshopUniv.jpg, UniInnHotel.png

**Comment by tramyn** [comment]
Thank you @jamesscottbrown for letting us know about [linkchecker](https://github.com/linkchecker/linkchecker); This is a very useful tool. 
I have gone through and address all of these broken links. 
If you are satisfied with these changes, feel free to close this issue. 
If not, let us know what we could do to resolve this issue. 
Thanks again for taking the time to report these broken links.

**Comment by jamesscottbrown** [comment]
Thanks for fixing these - they all seem fine now.
