### ISSUE TITLE
Should the NSF icon in the Glyphs tab for the SBOL website be a link?

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOL_website#32]
When clicking on the Glyphs tab and selecting SBOL Visual, the icons containing the different institutions involved in SBOL are not clickable besides the NSF icon and EPSRC icon.

Should we have a link to the NSF icon? 
If not, the ESPRC icon is currently linked to the NSF icon as well.

**Comment by cjmyers** [comment]
No links.
