### ISSUE TITLE
Provide application use case examples

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL_website#33]
One of the concerns that has been raised is that it may be unclear how SBOL 2.0 supports some common use case applications like registries, part search, measurement and characterizations. It would be useful to add a section that gives case studies (real or hypothetical), showing how SBOL 2.0 can be deployed to in support of such applications.

**Comment by cjmyers** [comment]
Should post demo and tutorial for a workflow.

**Comment by michael13162** [comment]
We could post the ISMB tutorial videos as an example of a case study.  Here are links:
https://drive.google.com/open?id=0Bx-ltjk2UJOSZlJhTFVMU2ctTEk
https://drive.google.com/open?id=0Bx-ltjk2UJOSeXRaTThYajdNV1k

This seems like it would fit quite well with "common use case applications like registries, part search, measurement and characterizations".

**Comment by tramyn** [comment]
The two videos that @michael13162 has suggested was uploaded by @mehersam  and @michael13162 and can be found on the [SBOL Youtube](https://www.youtube.com/channel/UCrxKZNvDVabwGoxEOMZt_Qg) channel. Another good example that was posted on our website to illustrate use case is the [Workflows page](http://sbolstandard.org/software/workflows/). However, we could still expand on this idea... 

@jakebeal @cjmyers @michael13162 @mehersam Any suggestions?

**Comment by cjmyers** [comment]
Check with Meher to see if any software survey pages include good videos showing use of software supporting SBOL.

**Comment by mehersam** [comment]
@tramyn I will go ahead and upload any videos after watching the demos given in the software survey responses that are appropriate to upload.
