### ISSUE TITLE
Propose a new glyph doesn't link to the page that tells you how to propose a new glyph

### ISSUE THREAD

**Issue by jamesamcl** [SynBioDex/SBOL_website#36]
Issue raised by Newcastle writing group.

**Comment by cjmyers** [comment]
Linked off new SBOL Visual page.  Still need a better interface for requesting new glyphs.  SEPs?

**Comment by jakebeal** [comment]
In discussion of the editors, we think an SEP-type process will be good, though the details will probably need to be a bit different.  We also think this shouldn't be launched until the SBOLv2 draft is better baked, however.

**Comment by cjmyers** [comment]
Does this mean we should remove the link to the Google Drive for proposing a new glyph for now?

Chris

**Comment by jakebeal** [comment]
No, leave it for now.  That's the current (dysfunctional) process, and we'll collect everything that's happened in it when we transition to the new process.

**Comment by tramyn** [comment]
@jakebeal 
What is the new process to propose a glyph? The README that is found in the Google Drive link indicates, 

"To contribute, first read the “How to Propose” document in the proposal folder for the type of proposal you want to make.  Then request editing permissions via email to editors@sbolstandard.org, with your name and a short description of your background."

Should this message be displayed in the SBOL Visual tab to instruct the user on how to propose a new glyph and then a link to the Google Drive?

**Comment by jakebeal** [comment]
Yes, although the whole thing needs to be revised and updated with SBOLv 2.0

**Comment by cjmyers** [comment]
I think this is fixed
