### ISSUE TITLE
Front page background figure is distracting and not related to SBOL

### ISSUE THREAD

**Issue by jamesamcl** [SynBioDex/SBOL_website#40]
Issue raised by Newcastle writing group.

**Comment by cjmyers** [comment]
Need to make sure that all links on scroll pictures go to meaningful information.  Contact is fine, but learn more goes to a poor about page.  Software goes to a defunct page that is not linked any other way.  Software should go to general overview about software workflows perhaps, or the FAQ once complete.

**Comment by cjmyers** [comment]
Broken links are fixed, but more thought needs to go into where we want to take people.
