### ISSUE TITLE
The SBOL visual background of the "software for synthetic biology" slide is not a good example and is placed in a weird place depending on browser window size

### ISSUE THREAD

**Issue by jamesamcl** [SynBioDex/SBOL_website#41]
Issue raised by Newcastle writing group.

**Comment by cjmyers** [comment]
Also should replace visual image with a better one from Pigeon or SBOLDesigner.

**Comment by michael13162** [comment]
![image](https://cloud.githubusercontent.com/assets/14242505/16274840/8fdf8284-3864-11e6-8cf8-b7f24fbbdd10.png)
This was created using SBOLDesigner's export to image feature.

**Comment by jamesamcl** [comment]
New figure looks good - can you export as SVG so it's resolution independent?

Sent from my iPhone

On Jun 22, 2016, at 5:28 PM, cjmyers <notifications@github.com<mailto:notifications@github.com>> wrote:

Also should replace visual image with a better one from Pigeon or SBOLDesigner.

##

**Comment by michael13162** [comment]
https://drive.google.com/open?id=0Bx-ltjk2UJOSbHNSdFJheUdRYlU

Here you go.

**Comment by mehersam** [comment]
The original picture is fixed on the front page. Also the figure that Michael provided is above is downloaded into Media, so it can replace the existing figure on the front page. I don't have access to change the picture, I believe the php page has to be changed? 

Possibly done.

**Comment by cjmyers** [comment]
Thanks.  We’ll need Bryan to help with updating the figure, then we can close this.

**Comment by michael13162** [comment]
![image](https://cloud.githubusercontent.com/assets/14242505/17186288/d517b99a-53f1-11e6-92df-09b3fb8dc4f8.png)
I think this still needs some formatting work.
