### ISSUE TITLE
sboljs library has no tutorial

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL_website#46]
The sboljs library has no tutorial linked from its page.

**Comment by tramyn** [comment]
@udp I was unable to find any examples or tutorials for the javascript library. Did you by any chance have any of this provided that you haven't uploaded onto our website? If not, could you please do this?

Also, I noticed when I clicked on "The Docs for sboljs are here" found on the sboljs page, it is navigating me to "Site not found" (http://ico2s.github.io/sboljs). This same error occurs when I go onto the sboljs website and clicked on Documentation mentioned on the last line of your README.md file (https://github.com/SynBioDex/sboljs).

**Comment by tramyn** [comment]
Issue now supported and updated with latest sbol data model v2.0.
