### ISSUE TITLE
The sboljs library has no sample project

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL_website#47]
The sboljs library has no sample project linked from its page

**Comment by tramyn** [comment]
@udp I was unable to find any examples or tutorials for the javascript library. Did you by any chance have any of this provided that you haven't uploaded onto our website? If not, could you please do this?

Also, I noticed when I clicked on "The Docs for sboljs are here" found on the [sboljs page](http://sbolstandard.org/software/libsbol/sboljs/), it is navigating me to "Site not found" (http://ico2s.github.io/sboljs). This same error occurs when I go onto the sboljs website and clicked on Documentation mentioned on the last line of your README.md file (https://github.com/SynBioDex/sboljs).

**Comment by tramyn** [comment]
@jakebeal What sample project are you referring to? Does sample project mean sample tutorials?

**Comment by tramyn** [comment]
@udp Do you have any end product of sample sboljs examples that we can include on the website? If so, could you provide this to me?

**Comment by jamesscottbrown** [comment]
The ``sboljs`` entry in the [SBOL Libraries page](http://sbolstandard.org/libsbol/) currently includes a link to a [CRISPR Circuit Example/Tutorial](http://sbolstandard.org/wp-content/uploads/2015/01/sboljs_tutorial.pdf) equivalent to those of the other libraries, so I think this issue has been resolved.
