### ISSUE TITLE
libSBOLc has no sample project

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL_website#49]
There is currently no sample project linked from the libSBOLc page.

**Comment by tramyn** [comment]
@jakebeal If you click on the link mentioned at "A code example for constructing a CRISPR circuit can be found here" on our C/C++ page, @bbartley has inserted a CRISPR example as a sample tutorial. Also, if you click on the link found on "Document can be found here", you will see some examples for constructing SBOL objects.
