### ISSUE TITLE
pySBOL has no documentation page

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL_website#50]
There is currently no API documentation linked from the pySBOL page.

**Comment by tramyn** [comment]
@jakebeal The link to pySBOL API is now mentioned in the pySBOL page found on our SBOL website (http://sbolstandard.org/software/libSBOL/python-pysbol/) mentioned in the Documentation bullet point. This link was updated by @bbartley and I have confirmed the link that it is working.
