### ISSUE TITLE
pySBOL has no tutorial

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL_website#51]
There is currently no tutorial linked from the pySBOL page.

**Comment by tramyn** [comment]
@jakebeal If you click on the link mentioned at "A code example for constructing a CRISPR circuit can be found here"  on our [pySBOL tab](http://sbolstandard.org/software/libSBOL/python-pysbol/), @bbartley has inserted a CRISPR example as a sample tutorial. Also, if you click on the link found on "Document can be found here", you will see some examples for constructing SBOL objects.
