### ISSUE TITLE
Specification pages should have links to github

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL_website#58]
The specification pages should have links to github for the source and issue tracker.  There should also be the citation listed there.  See Java library for example.

**Comment by mehersam** [comment]
Should now have links to specification document and if relevant, the citation and link to issue tracker.

**Comment by mehersam** [comment]
Updated Specification pages to correct publication citation, removed all issue tracker links from all version except latest, fixed typo on SBOL Visual first bullet, added a link to the latest release of SBOL 2.0.1.

**Comment by mehersam** [comment]
Done.

**Comment by cjmyers** [comment]
Tweaked a bit the format.  Closing.
