### ISSUE TITLE
SBOL Visual Page

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL_website#59]
Change menu from Glyphs to Visual

Make the Visual page be a bulleted list of links to additional information.  Everything on current page, plus link to the Propose a New Glyph page.

**Comment by mehersam** [comment]
Visual page is updated to a bulleted list of links to additional information and a link to the Propose a New Glyph page has been added. Could not figure out how to access the Menus and change 'Glyphs' to 'Visual' and remove 'Propose a New Glyph' as a link in the subheadings.
