### ISSUE TITLE
Need an SBOL Visual Specification github links

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL_website#63]
Need an SBOL Visual github link for the source and the issue tracker for the latest version of the specification.

**Comment by jakebeal** [comment]
I have created an SBOLv github repository here: https://github.com/SynBioDex/SBOL-visual
I have linked to the issues page from the webpage, but do not think we should post the source link directly yet since it's an unfinished draft, not a "latest version" at present.
