### ISSUE TITLE
Improve website footer (tweets + SBOL supporters)

### ISSUE THREAD

**Issue by minnatwang** [SynBioDex/SBOL_website#68]
Most pages have minimal content, which means the footer (tweets + CBOL supporters) ends up taking up half the page. Text size within the footer is also variable, which makes it difficult to read. Here are the ways I suggest improving it:
* Move the Tweets widget either to the right side bar or to the same row as the supporters
* Name the three largest supporters to the SBOL projects, move all other names and logos to a new section in the About tab (unless it's written into the licenses and agreements that these institutions all need to be named on every page).
* Resize text to be consistent font size

**Comment by 3ach** [comment]
Change tweets to an icon for the twitter account
