### ISSUE TITLE
Table of Glyphs page doesn't have a table of glyphs

### ISSUE THREAD

**Issue by minnatwang** [SynBioDex/SBOL_website#77]
Table of glyphs page (http://sbolstandard.org/sbol-glyph-set/) has no table of glyphs, only a line of code

**Comment by tramyn** [comment]
This issue can be replicated by clicking on the SBOL Visual tab. Then, click on this link that indicates, "Thumbnails SBOL Visual glyphs in various formats can be downloaded".  On the left hand side of the page, there should be a link that says "Table of Glyphs".

<img width="1415" alt="glyph_table" src="https://cloud.githubusercontent.com/assets/7537729/21994535/6345bcbc-dbdd-11e6-8190-fa56092d0901.png">

This is now fixed although the information in this link is redundant with the main link when clicking on SBOL Visual tab.
