### ISSUE TITLE
Outreach page needs improvement

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL_website#81]
The outreach page should include information about our outreach efforts.  Every workshop, tutorial, and even invited talk we give should be linked here.  It should be clear that we are going out and spreading the word.  Also, have the materials linked so those that missed it, can get the slides.

**Comment by tramyn** [comment]
This issue is addressed in issue #85 .

**Comment by cjmyers** [comment]
Let's remove the 6th, 7th, etc. as it is very inconsistent.  Also, I thought there would be links to slides from some of these not just programs.

**Comment by tramyn** [comment]
@cjmyers I have removed the 6th, 7th off of each outreach event. I have all the information to insert the slides and names of presenters to the outreach and meetings table. The code that I need to setup on Wordpress is taking some time since I want the table to expand and shrink based on the event selected and then display all the names of the presenters and presentations.

**Comment by tramyn** [comment]
@cjmyers I would like to take a moment to express how frustrated I was to get this feature working. Providing name of presenters and their presentation is now supported on the outreach and meetings table!!!! Based on this feature, it will allow future add-ons of meetings and events to look more compact. Only the essential information is shown. More detailed information is presented after clicking on the green plus sign. 

This is how it works:
Click on the green plus sign to look at the presenters and their presentation that they gave at the specified conference/workshop.  Each name of the presentation has a link that will directly navigate the user to their slides/poster that was given by the author stored on out SBOL community media repo. 

This feature can be found on both the [Meetings](http://sbolstandard.org/development/meetings/) and [Outreach](http://sbolstandard.org/development/outreach/) page on our SBOL website. 

I am very proud of this feature so please have a look. If you are satisfied with the content on these two pages, please close this issue.

**Comment by cjmyers** [comment]
You should be proud.  This is awesome!  Thanks much.
