### ISSUE TITLE
Some outreach events missing from website

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL_website#85]
The IWBDA Seattle workshop is missing from website.
The ISMB workshop is missing from website.

Let's move all outreach events from meetings page to outreach and add these and any others we can think of.  We have given several invited talks on SBOL, the talks should be linked here.  Ones I can think off are: SB6.0, SEED, IWBDA (several), ISMB, Harmony 2016, COMBINE 2014/2015/2016, ICSB 2014 tutorial.

**Comment by tramyn** [comment]
@cjmyers : Do you want to move this entire table found on Community->Meetings tab to Community->Outreach tab? If so, what will be in the Meetings tab? If not, what are your ideas on your suggestion?

<img width="1041" alt="outreach_table" src="https://cloud.githubusercontent.com/assets/7537729/21973450/026923ca-db7e-11e6-9bdb-451a85328117.png">

Also , if we move contents from Meetings tab to Outreach tab, will this resolve issue #81 ?

**Comment by cjmyers** [comment]
No, not the entire table.  I was only hoping to include Outreach events and not our working meetings.  This would be the Newcastle Introductory SBOL Workshop, the ISMB special session that Kevin organized, IWBDA 2015’s special session on SBOL, and any other training like events for SBOL.

Chris

**Comment by tramyn** [comment]
@cjmyers : The SBOL website should now reflect this change. I have updated the table in the Community->Meetings tab such that the table is not hard coded but rather flexible for adding future meetings to the page and sorting of the list. All meetings listed reflected the old table that was on the website and should be up to date (http://sbolstandard.org/development/meetings/).

Also, the Community->Outreach tab is now filled with outreach events that SBOL has participated in. It currently has a short description of the page and table's purpose that could be further explained. All events listed should be up to date (http://sbolstandard.org/development/outreach/).

If you are satisfied with these changes, could you please close this issue?

**Comment by cjmyers** [comment]
Done
