### ISSUE TITLE
Upload videos of compiling examples on different IDE tool

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOL_website#99]
Videos on how to compile a simple example using Visual Studio etc.

**Comment by cjmyers** [comment]
Move this to the library issue trackers.

**Comment by tramyn** [comment]
This issue request is now redirected to each SBOL library:
[sboljs](https://github.com/SynBioDex/sboljs/issues/10), [libSBOL (C, C++)](https://github.com/SynBioDex/libSBOL/issues/142), [pySBOL (python)](https://github.com/SynBioDex/pySBOL/issues/43), and [libSBOLj (java)](https://github.com/SynBioDex/libSBOLj/issues/443)
